In [1]:
import numpy as np

## DataTypes and Attributes

In [2]:
# Numpy main datatype is nd - array

a1 = np.array([1,2,3])

a1

array([1, 2, 3])

In [3]:
type(a1)  

numpy.ndarray

In [4]:
a2 = np.array([
    [1,2.0, 3],
    [4,5,6.5],
])
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [5]:
type(a2)

numpy.ndarray

In [7]:
#3 d array

a3 = np.array([
    [ 
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ]
    
])

a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [11]:
a2.shape

(2, 3)

In [12]:
a3.shape

(2, 3, 3)

In [14]:
a1.ndim, a2.ndim, a3.ndim # ndim tells the dimension of array

(1, 2, 3)

# to check datatypes of array

In [15]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

# to get the number of element in array or matrix

In [16]:
a1.size, a2.size, a3.size

(3, 6, 18)

# Create Dataframe from Numpy

In [17]:
import pandas as pd

In [18]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5